server {
    listen 80;
    root /usr/share/nginx/html;
    location / { try_files $uri $uri/ /index.html; add_header Cache-Control "no-store"; }
    location /api/ { proxy_pass http://edutwin-acceptance-api:8080/api/; }
}
