export const permissions = {
  teachersRead: "organization.teachers.read",
  teachersCreate: "organization.teachers.create",
  studentsRead: "organization.students.read",
  studentsCreate: "organization.students.create",
  classesRead: "organization.classes.read",
  classesCreate: "organization.classes.create",
  subjectsRead: "knowledge.subjects.read",
  nodesRead: "knowledge.nodes.read",
  nodesCreate: "knowledge.nodes.create",
  edgesRead: "knowledge.edges.read",
  edgesCreate: "knowledge.edges.create",
  curriculumsRead: "curriculum.curriculums.read",
  curriculumsCreate: "curriculum.curriculums.create",
  curriculumsUpdate: "curriculum.curriculums.update",
  questionsRead: "curriculum.questions.read",
  questionsCreate: "curriculum.questions.create",
  questionsUpdate: "curriculum.questions.update",
  questionsPublish: "curriculum.questions.publish",
  assignmentsRead: "assignments.assignments.read",
  assignmentsCreate: "assignments.assignments.create",
  assignmentsUpdate: "assignments.assignments.update",
  rolesRead: "authorization.roles.read",
  rolesCreate: "authorization.roles.create",
  rolesUpdate: "authorization.roles.update",
  rolesArchive: "authorization.roles.archive",
  rolesManagePermissions: "authorization.roles.manage_permissions",
  permissionsRead: "authorization.permissions.read",
  userRolesRead: "authorization.user_roles.read",
  userRolesAssign: "authorization.user_roles.assign",
  auditRead: "authorization.audit.read",
} as const;

export const authorizationUiPermissions = [
  permissions.rolesRead,
  permissions.permissionsRead,
  permissions.userRolesRead,
  permissions.auditRead,
] as const;
