// <auto-generated />
using System;
using EduTwin.DAL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduTwin.DAL.Persistence.Migrations
{
    [DbContext(typeof(EduTwinDbContext))]
    [Migration("20260715154837_AddKnowledgeCurriculumQuestionsAssignments")]
    partial class AddKnowledgeCurriculumQuestionsAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EduTwin.DAL.Assignments.Assignment", b =>
                {
                    b.Property<string>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("assignment_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByTeacherId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by_teacher_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_at");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("AssignmentId")
                        .HasName("pk_assignments");

                    b.HasAlternateKey("CenterId", "AssignmentId")
                        .HasName("ux_assignments_center_id_assignment_id");

                    b.HasIndex("CenterId", "CreatedByTeacherId")
                        .HasDatabaseName("ix_assignments_center_id_created_by_teacher_id");

                    b.HasIndex("CenterId", "ClassId", "Status", "DueAt")
                        .HasDatabaseName("ix_assignments_center_id_class_id_status_due_at");

                    b.ToTable("assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignments_status", "status IN ('Draft', 'Published', 'Closed', 'Archived')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Assignments.AssignmentQuestion", b =>
                {
                    b.Property<string>("CenterId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("AssignmentId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("assignment_id");

                    b.Property<ulong>("QuestionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("question_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<uint>("OrderIndex")
                        .HasColumnType("int unsigned")
                        .HasColumnName("order_index");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("points");

                    b.HasKey("CenterId", "AssignmentId", "QuestionId")
                        .HasName("pk_assignment_questions");

                    b.HasIndex("CenterId", "QuestionId")
                        .HasDatabaseName("ix_assignment_questions_center_id_question_id");

                    b.HasIndex("CenterId", "AssignmentId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_assignment_questions_center_id_assignment_id_order_index");

                    b.ToTable("assignment_questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignment_questions_points", "points > 0");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Assignments.AssignmentTarget", b =>
                {
                    b.Property<string>("CenterId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("AssignmentId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("assignment_id");

                    b.Property<string>("StudentId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("TargetSource")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("target_source");

                    b.HasKey("CenterId", "AssignmentId", "StudentId")
                        .HasName("pk_assignment_targets");

                    b.HasIndex("CenterId", "StudentId")
                        .HasDatabaseName("ix_assignment_targets_center_id_student_id");

                    b.ToTable("assignment_targets", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignment_targets_target_source", "target_source IN ('WholeClass', 'SelectedStudents', 'GapGroup')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Assignments.StudentAssignmentProgress", b =>
                {
                    b.Property<ulong>("ProgressId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("progress_id");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("assignment_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<uint>("CompletedQuestionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("completed_question_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<uint>("TotalQuestionCount")
                        .HasColumnType("int unsigned")
                        .HasColumnName("total_question_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("ProgressId")
                        .HasName("pk_student_assignment_progress");

                    b.HasIndex("CenterId", "AssignmentId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ux_student_assignment_progress_center_assignment_id_student_id");

                    b.HasIndex("CenterId", "StudentId", "Status")
                        .HasDatabaseName("ix_student_assignment_progress_center_id_student_id_status");

                    b.ToTable("student_assignment_progress", null, t =>
                        {
                            t.HasCheckConstraint("ck_student_assignment_progress_counts", "completed_question_count <= total_question_count");

                            t.HasCheckConstraint("ck_student_assignment_progress_status", "status IN ('NotStarted', 'InProgress', 'Completed', 'Overdue')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.Curriculum", b =>
                {
                    b.Property<string>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("review_status");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("SourceFile")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("source_file");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("CurriculumId")
                        .HasName("pk_curriculums");

                    b.HasAlternateKey("CenterId", "CurriculumId")
                        .HasName("ux_curriculums_center_id_curriculum_id");

                    b.HasIndex("CenterId", "SubjectId", "ReviewStatus")
                        .HasDatabaseName("ix_curriculums_center_id_subject_id_review_status");

                    b.HasIndex("CenterId", "TeacherId", "ReviewStatus")
                        .HasDatabaseName("ix_curriculums_center_id_teacher_id_review_status");

                    b.ToTable("curriculums", null, t =>
                        {
                            t.HasCheckConstraint("ck_curriculums_review_status", "review_status IN ('Draft', 'Published', 'Archived')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.CurriculumClass", b =>
                {
                    b.Property<string>("CenterId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("CurriculumId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("ClassId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("assigned_by");

                    b.HasKey("CenterId", "CurriculumId", "ClassId")
                        .HasName("pk_curriculum_classes");

                    b.HasIndex("CenterId", "ClassId")
                        .HasDatabaseName("ix_curriculum_classes_center_id_class_id");

                    b.ToTable("curriculum_classes", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.CurriculumNode", b =>
                {
                    b.Property<string>("CenterId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("CurriculumId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("curriculum_id");

                    b.Property<ulong>("NodeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("node_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<uint>("OrderIndex")
                        .HasColumnType("int unsigned")
                        .HasColumnName("order_index");

                    b.HasKey("CenterId", "CurriculumId", "NodeId")
                        .HasName("pk_curriculum_nodes");

                    b.HasIndex("CenterId", "NodeId")
                        .HasDatabaseName("ix_curriculum_nodes_center_id_node_id");

                    b.HasIndex("CenterId", "CurriculumId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_curriculum_nodes_center_id_curriculum_id_order_index");

                    b.ToTable("curriculum_nodes", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.Question", b =>
                {
                    b.Property<ulong>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("question_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByTeacherId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by_teacher_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("deleted_by");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("difficulty");

                    b.Property<uint>("EstimatedTimeSeconds")
                        .HasColumnType("int unsigned")
                        .HasColumnName("estimated_time_seconds");

                    b.Property<string>("ExpectedReasoning")
                        .HasColumnType("longtext")
                        .HasColumnName("expected_reasoning");

                    b.Property<string>("GradingCriteria")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("grading_criteria");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("language_code");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1.00m)
                        .HasColumnName("max_score");

                    b.Property<ulong>("PrimaryTopicNodeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("primary_topic_node_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("question_type");

                    b.Property<bool>("ReasoningRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("reasoning_required");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("solution");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("QuestionId")
                        .HasName("pk_questions");

                    b.HasAlternateKey("CenterId", "QuestionId")
                        .HasName("ux_questions_center_id_question_id");

                    b.HasIndex("CenterId", "PrimaryTopicNodeId")
                        .HasDatabaseName("ix_questions_center_id_primary_topic_node_id");

                    b.HasIndex("CenterId", "CreatedByTeacherId", "Status")
                        .HasDatabaseName("ix_questions_center_id_created_by_teacher_id_status");

                    b.HasIndex("CenterId", "SubjectId", "PrimaryTopicNodeId", "Status", "Difficulty")
                        .HasDatabaseName("ix_questions_center_id_subject_id_topic_id_status_difficulty");

                    b.ToTable("questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_questions_difficulty", "difficulty BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_questions_estimated_time_seconds", "estimated_time_seconds > 0");

                            t.HasCheckConstraint("ck_questions_language_code", "language_code IN ('vi', 'en')");

                            t.HasCheckConstraint("ck_questions_max_score", "max_score > 0");

                            t.HasCheckConstraint("ck_questions_question_type", "question_type IN ('MultipleChoice', 'ShortAnswer', 'Essay')");

                            t.HasCheckConstraint("ck_questions_status", "status IN ('Draft', 'Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.QuestionKnowledgeNode", b =>
                {
                    b.Property<string>("CenterId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<ulong>("QuestionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("question_id");

                    b.Property<ulong>("NodeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("node_id");

                    b.Property<string>("MappingRole")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("mapping_role");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("CenterId", "QuestionId", "NodeId", "MappingRole")
                        .HasName("pk_question_knowledge_nodes");

                    b.HasIndex("CenterId", "NodeId")
                        .HasDatabaseName("ix_question_knowledge_nodes_center_id_node_id");

                    b.ToTable("question_knowledge_nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_question_knowledge_nodes_mapping_role", "mapping_role IN ('Primary', 'Secondary', 'Prerequisite')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.QuestionOption", b =>
                {
                    b.Property<ulong>("OptionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("option_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_correct");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("option_label");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_text");

                    b.Property<uint>("OrderIndex")
                        .HasColumnType("int unsigned")
                        .HasColumnName("order_index");

                    b.Property<ulong>("QuestionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("question_id");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("OptionId")
                        .HasName("pk_question_options");

                    b.HasIndex("CenterId", "QuestionId", "OptionLabel")
                        .IsUnique()
                        .HasDatabaseName("ux_question_options_center_id_question_id_option_label");

                    b.HasIndex("CenterId", "QuestionId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_question_options_center_id_question_id_order_index");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.RefreshToken", b =>
                {
                    b.Property<ulong>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("refresh_token_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("expires_at");

                    b.Property<ulong?>("ReplacedByTokenId")
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("CHAR(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshTokenId")
                        .HasName("pk_refresh_tokens");

                    b.HasAlternateKey("CenterId", "RefreshTokenId")
                        .HasName("ux_refresh_tokens_center_id_refresh_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("CenterId", "ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_center_id_replaced_by_token_id");

                    b.HasIndex("CenterId", "UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_center_id_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("user_id");

                    b.Property<uint>("AuthVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT UNSIGNED")
                        .HasDefaultValue(1u)
                        .HasColumnName("auth_version");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("role_name");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasAlternateKey("CenterId", "UserId")
                        .HasName("ux_users_center_id_user_id");

                    b.HasIndex("CenterId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_center_id_username");

                    b.HasIndex("CenterId", "RoleName", "Status")
                        .HasDatabaseName("ix_users_center_id_role_name_status");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role_name", "role_name IN ('Student', 'Teacher', 'CenterManager')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('Active', 'Locked', 'Disabled')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.KnowledgeGraph.KnowledgeEdge", b =>
                {
                    b.Property<ulong>("EdgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("edge_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("relation_type");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<ulong>("SourceNodeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("source_node_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<ulong>("TargetNodeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("target_node_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1.00m)
                        .HasColumnName("weight");

                    b.HasKey("EdgeId")
                        .HasName("pk_knowledge_edges");

                    b.HasIndex("CenterId", "EdgeId")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_edges_center_id_edge_id");

                    b.HasIndex("CenterId", "SourceNodeId")
                        .HasDatabaseName("ix_knowledge_edges_center_id_source_node_id");

                    b.HasIndex("CenterId", "SubjectId")
                        .HasDatabaseName("ix_knowledge_edges_center_id_subject_id");

                    b.HasIndex("CenterId", "TargetNodeId", "RelationType")
                        .HasDatabaseName("ix_knowledge_edges_center_id_target_node_id_relation_type");

                    b.HasIndex("CenterId", "SourceNodeId", "TargetNodeId", "RelationType")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_edges_center_id_source_id_target_id_relation_type");

                    b.ToTable("knowledge_edges", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_edges_relation_type", "relation_type IN ('PrerequisiteOf', 'RelatedTo', 'PartOf', 'CausesErrorIn')");

                            t.HasCheckConstraint("ck_knowledge_edges_self_loop", "source_node_id <> target_node_id");

                            t.HasCheckConstraint("ck_knowledge_edges_weight", "weight BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.KnowledgeGraph.KnowledgeNode", b =>
                {
                    b.Property<ulong>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("node_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<uint>("EstimatedLearningMinutes")
                        .HasColumnType("int unsigned")
                        .HasColumnName("estimated_learning_minutes");

                    b.Property<decimal>("ExamImportance")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("exam_importance");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("node_code");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("node_name");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("node_type");

                    b.Property<uint>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("order_index");

                    b.Property<ulong?>("ParentNodeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("parent_node_id");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("NodeId")
                        .HasName("pk_knowledge_nodes");

                    b.HasAlternateKey("CenterId", "NodeId")
                        .HasName("ux_knowledge_nodes_center_id_node_id");

                    b.HasIndex("CenterId", "ParentNodeId")
                        .HasDatabaseName("ix_knowledge_nodes_center_id_parent_node_id");

                    b.HasIndex("CenterId", "SubjectId", "NodeCode")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_nodes_center_id_subject_id_node_code");

                    b.HasIndex("CenterId", "SubjectId", "NodeType", "OrderIndex")
                        .HasDatabaseName("ix_knowledge_nodes_center_id_subject_id_node_type_order_index");

                    b.ToTable("knowledge_nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_nodes_estimated_learning_minutes", "estimated_learning_minutes > 0");

                            t.HasCheckConstraint("ck_knowledge_nodes_exam_importance", "exam_importance BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_knowledge_nodes_node_type", "node_type IN ('Subject', 'Chapter', 'Topic', 'Skill', 'Concept')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Center", b =>
                {
                    b.Property<string>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("CenterCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("center_code");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("center_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(64)")
                        .HasDefaultValue("Asia/Bangkok")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("CenterId")
                        .HasName("pk_centers");

                    b.HasIndex("CenterCode")
                        .IsUnique()
                        .HasDatabaseName("ux_centers_center_code");

                    b.ToTable("centers", null, t =>
                        {
                            t.HasCheckConstraint("ck_centers_status", "status IN ('Active', 'Suspended')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Class", b =>
                {
                    b.Property<string>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("class_id");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("academic_year");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("ClassId")
                        .HasName("pk_classes");

                    b.HasAlternateKey("CenterId", "ClassId")
                        .HasName("ux_classes_center_id_class_id");

                    b.HasIndex("CenterId", "ClassName", "AcademicYear")
                        .IsUnique()
                        .HasDatabaseName("ux_classes_center_id_class_name_academic_year");

                    b.HasIndex("CenterId", "SubjectId", "Status")
                        .HasDatabaseName("ix_classes_center_id_subject_id_status");

                    b.HasIndex("CenterId", "TeacherId", "Status")
                        .HasDatabaseName("ix_classes_center_id_teacher_id_status");

                    b.ToTable("classes", null, t =>
                        {
                            t.HasCheckConstraint("ck_classes_status", "status IN ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.ClassStudent", b =>
                {
                    b.Property<string>("CenterId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("ClassId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("class_id");

                    b.Property<string>("StudentId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("removed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("status");

                    b.HasKey("CenterId", "ClassId", "StudentId")
                        .HasName("pk_class_students");

                    b.HasIndex("CenterId", "StudentId", "Status")
                        .HasDatabaseName("ix_class_students_center_id_student_id_status");

                    b.ToTable("class_students", null, t =>
                        {
                            t.HasCheckConstraint("ck_class_students_status", "status IN ('Active', 'Removed')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("full_name");

                    b.Property<byte>("GradeLevel")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("grade_level");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("StudentId")
                        .HasName("pk_students");

                    b.HasAlternateKey("CenterId", "StudentId")
                        .HasName("ux_students_center_id_student_id");

                    b.HasIndex("CenterId", "GradeLevel")
                        .HasDatabaseName("ix_students_center_id_grade_level");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("ck_students_grade_level", "grade_level BETWEEN 10 AND 12");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("subject_code");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("subject_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("SubjectId")
                        .HasName("pk_subjects");

                    b.HasAlternateKey("CenterId", "SubjectId")
                        .HasName("ux_subjects_center_id_subject_id");

                    b.HasIndex("CenterId", "SubjectCode")
                        .IsUnique()
                        .HasDatabaseName("ux_subjects_center_id_subject_code");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Bio")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("bio");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Department")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("department");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("TeacherId")
                        .HasName("pk_teachers");

                    b.HasAlternateKey("CenterId", "TeacherId")
                        .HasName("ux_teachers_center_id_teacher_id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.Assignments.Assignment", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Class", "Class")
                        .WithMany()
                        .HasForeignKey("CenterId", "ClassId")
                        .HasPrincipalKey("CenterId", "ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_classes_class");

                    b.HasOne("EduTwin.DAL.Organization.Teacher", "CreatedByTeacher")
                        .WithMany()
                        .HasForeignKey("CenterId", "CreatedByTeacherId")
                        .HasPrincipalKey("CenterId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_teachers_created_by_teacher");

                    b.Navigation("Class");

                    b.Navigation("CreatedByTeacher");
                });

            modelBuilder.Entity("EduTwin.DAL.Assignments.AssignmentQuestion", b =>
                {
                    b.HasOne("EduTwin.DAL.Assignments.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("CenterId", "AssignmentId")
                        .HasPrincipalKey("CenterId", "AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_questions_assignments_assignment");

                    b.HasOne("EduTwin.DAL.CurriculumAndQuestions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("CenterId", "QuestionId")
                        .HasPrincipalKey("CenterId", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_questions_questions_question");

                    b.Navigation("Assignment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EduTwin.DAL.Assignments.AssignmentTarget", b =>
                {
                    b.HasOne("EduTwin.DAL.Assignments.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("CenterId", "AssignmentId")
                        .HasPrincipalKey("CenterId", "AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_targets_assignments_assignment");

                    b.HasOne("EduTwin.DAL.Organization.Student", "Student")
                        .WithMany()
                        .HasForeignKey("CenterId", "StudentId")
                        .HasPrincipalKey("CenterId", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_targets_students_student");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTwin.DAL.Assignments.StudentAssignmentProgress", b =>
                {
                    b.HasOne("EduTwin.DAL.Assignments.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("CenterId", "AssignmentId")
                        .HasPrincipalKey("CenterId", "AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_assignment_progress_assignments_assignment");

                    b.HasOne("EduTwin.DAL.Organization.Student", "Student")
                        .WithMany()
                        .HasForeignKey("CenterId", "StudentId")
                        .HasPrincipalKey("CenterId", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_assignment_progress_students_student");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.Curriculum", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("CenterId", "SubjectId")
                        .HasPrincipalKey("CenterId", "SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curriculums_subjects_subject");

                    b.HasOne("EduTwin.DAL.Organization.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("CenterId", "TeacherId")
                        .HasPrincipalKey("CenterId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curriculums_teachers_teacher");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.CurriculumClass", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Class", "Class")
                        .WithMany()
                        .HasForeignKey("CenterId", "ClassId")
                        .HasPrincipalKey("CenterId", "ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curriculum_classes_classes_class");

                    b.HasOne("EduTwin.DAL.CurriculumAndQuestions.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CenterId", "CurriculumId")
                        .HasPrincipalKey("CenterId", "CurriculumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curriculum_classes_curriculums_curriculum");

                    b.Navigation("Class");

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.CurriculumNode", b =>
                {
                    b.HasOne("EduTwin.DAL.CurriculumAndQuestions.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CenterId", "CurriculumId")
                        .HasPrincipalKey("CenterId", "CurriculumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curriculum_nodes_curriculums_curriculum");

                    b.HasOne("EduTwin.DAL.KnowledgeGraph.KnowledgeNode", "Node")
                        .WithMany()
                        .HasForeignKey("CenterId", "NodeId")
                        .HasPrincipalKey("CenterId", "NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curriculum_nodes_knowledge_nodes_node");

                    b.Navigation("Curriculum");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.Question", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Teacher", "CreatedByTeacher")
                        .WithMany()
                        .HasForeignKey("CenterId", "CreatedByTeacherId")
                        .HasPrincipalKey("CenterId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_teachers_created_by_teacher");

                    b.HasOne("EduTwin.DAL.KnowledgeGraph.KnowledgeNode", "PrimaryTopicNode")
                        .WithMany()
                        .HasForeignKey("CenterId", "PrimaryTopicNodeId")
                        .HasPrincipalKey("CenterId", "NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_knowledge_nodes_primary_topic");

                    b.HasOne("EduTwin.DAL.Organization.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("CenterId", "SubjectId")
                        .HasPrincipalKey("CenterId", "SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_subjects_subject");

                    b.Navigation("CreatedByTeacher");

                    b.Navigation("PrimaryTopicNode");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.QuestionKnowledgeNode", b =>
                {
                    b.HasOne("EduTwin.DAL.KnowledgeGraph.KnowledgeNode", "Node")
                        .WithMany()
                        .HasForeignKey("CenterId", "NodeId")
                        .HasPrincipalKey("CenterId", "NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_question_knowledge_nodes_knowledge_nodes_node");

                    b.HasOne("EduTwin.DAL.CurriculumAndQuestions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("CenterId", "QuestionId")
                        .HasPrincipalKey("CenterId", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_question_knowledge_nodes_questions_question");

                    b.Navigation("Node");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EduTwin.DAL.CurriculumAndQuestions.QuestionOption", b =>
                {
                    b.HasOne("EduTwin.DAL.CurriculumAndQuestions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("CenterId", "QuestionId")
                        .HasPrincipalKey("CenterId", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_questions_question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.RefreshToken", b =>
                {
                    b.HasOne("EduTwin.DAL.IdentityAndTenancy.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("CenterId", "ReplacedByTokenId")
                        .HasPrincipalKey("CenterId", "RefreshTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by");

                    b.HasOne("EduTwin.DAL.IdentityAndTenancy.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("CenterId", "UserId")
                        .HasPrincipalKey("CenterId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_tenant");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.User", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_centers_tenant");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("EduTwin.DAL.KnowledgeGraph.KnowledgeEdge", b =>
                {
                    b.HasOne("EduTwin.DAL.KnowledgeGraph.KnowledgeNode", "SourceNode")
                        .WithMany()
                        .HasForeignKey("CenterId", "SourceNodeId")
                        .HasPrincipalKey("CenterId", "NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_edges_knowledge_nodes_source");

                    b.HasOne("EduTwin.DAL.Organization.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("CenterId", "SubjectId")
                        .HasPrincipalKey("CenterId", "SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_edges_subjects_subject");

                    b.HasOne("EduTwin.DAL.KnowledgeGraph.KnowledgeNode", "TargetNode")
                        .WithMany()
                        .HasForeignKey("CenterId", "TargetNodeId")
                        .HasPrincipalKey("CenterId", "NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_edges_knowledge_nodes_target");

                    b.Navigation("SourceNode");

                    b.Navigation("Subject");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("EduTwin.DAL.KnowledgeGraph.KnowledgeNode", b =>
                {
                    b.HasOne("EduTwin.DAL.KnowledgeGraph.KnowledgeNode", "ParentNode")
                        .WithMany()
                        .HasForeignKey("CenterId", "ParentNodeId")
                        .HasPrincipalKey("CenterId", "NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_knowledge_nodes_knowledge_nodes_parent");

                    b.HasOne("EduTwin.DAL.Organization.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("CenterId", "SubjectId")
                        .HasPrincipalKey("CenterId", "SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_nodes_subjects_subject");

                    b.Navigation("ParentNode");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Class", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("CenterId", "SubjectId")
                        .HasPrincipalKey("CenterId", "SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_subjects_subject");

                    b.HasOne("EduTwin.DAL.Organization.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("CenterId", "TeacherId")
                        .HasPrincipalKey("CenterId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_teachers_teacher");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.ClassStudent", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Class", "Class")
                        .WithMany("ClassStudents")
                        .HasForeignKey("CenterId", "ClassId")
                        .HasPrincipalKey("CenterId", "ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_students_classes_class");

                    b.HasOne("EduTwin.DAL.Organization.Student", "Student")
                        .WithMany()
                        .HasForeignKey("CenterId", "StudentId")
                        .HasPrincipalKey("CenterId", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_students_students_student");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Student", b =>
                {
                    b.HasOne("EduTwin.DAL.IdentityAndTenancy.User", "User")
                        .WithOne()
                        .HasForeignKey("EduTwin.DAL.Organization.Student", "CenterId", "StudentId")
                        .HasPrincipalKey("EduTwin.DAL.IdentityAndTenancy.User", "CenterId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_users_profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Subject", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_centers_tenant");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Teacher", b =>
                {
                    b.HasOne("EduTwin.DAL.IdentityAndTenancy.User", "User")
                        .WithOne()
                        .HasForeignKey("EduTwin.DAL.Organization.Teacher", "CenterId", "TeacherId")
                        .HasPrincipalKey("EduTwin.DAL.IdentityAndTenancy.User", "CenterId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_users_profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Class", b =>
                {
                    b.Navigation("ClassStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
