// <auto-generated />
using System;
using EduTwin.DAL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduTwin.DAL.Persistence.Migrations
{
    [DbContext(typeof(EduTwinDbContext))]
    partial class EduTwinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.RefreshToken", b =>
                {
                    b.Property<ulong>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("refresh_token_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("expires_at");

                    b.Property<ulong?>("ReplacedByTokenId")
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("CHAR(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshTokenId")
                        .HasName("pk_refresh_tokens");

                    b.HasAlternateKey("CenterId", "RefreshTokenId")
                        .HasName("ux_refresh_tokens_center_id_refresh_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("CenterId", "ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_center_id_replaced_by_token_id");

                    b.HasIndex("CenterId", "UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_center_id_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("user_id");

                    b.Property<uint>("AuthVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT UNSIGNED")
                        .HasDefaultValue(1u)
                        .HasColumnName("auth_version");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("role_name");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasAlternateKey("CenterId", "UserId")
                        .HasName("ux_users_center_id_user_id");

                    b.HasIndex("CenterId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_center_id_username");

                    b.HasIndex("CenterId", "RoleName", "Status")
                        .HasDatabaseName("ix_users_center_id_role_name_status");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role_name", "role_name IN ('Student', 'Teacher', 'CenterManager')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('Active', 'Locked', 'Disabled')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Center", b =>
                {
                    b.Property<string>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("CenterCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("center_code");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("center_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(64)")
                        .HasDefaultValue("Asia/Bangkok")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("CenterId")
                        .HasName("pk_centers");

                    b.HasIndex("CenterCode")
                        .IsUnique()
                        .HasDatabaseName("ux_centers_center_code");

                    b.ToTable("centers", null, t =>
                        {
                            t.HasCheckConstraint("ck_centers_status", "status IN ('Active', 'Suspended')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Class", b =>
                {
                    b.Property<string>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("class_id");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("academic_year");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("ClassId")
                        .HasName("pk_classes");

                    b.HasAlternateKey("CenterId", "ClassId")
                        .HasName("ux_classes_center_id_class_id");

                    b.HasIndex("CenterId", "ClassName", "AcademicYear")
                        .IsUnique()
                        .HasDatabaseName("ux_classes_center_id_class_name_academic_year");

                    b.HasIndex("CenterId", "SubjectId", "Status")
                        .HasDatabaseName("ix_classes_center_id_subject_id_status");

                    b.HasIndex("CenterId", "TeacherId", "Status")
                        .HasDatabaseName("ix_classes_center_id_teacher_id_status");

                    b.ToTable("classes", null, t =>
                        {
                            t.HasCheckConstraint("ck_classes_status", "status IN ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.ClassStudent", b =>
                {
                    b.Property<string>("CenterId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<string>("ClassId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("class_id");

                    b.Property<string>("StudentId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("removed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("status");

                    b.HasKey("CenterId", "ClassId", "StudentId")
                        .HasName("pk_class_students");

                    b.HasIndex("CenterId", "StudentId", "Status")
                        .HasDatabaseName("ix_class_students_center_id_student_id_status");

                    b.ToTable("class_students", null, t =>
                        {
                            t.HasCheckConstraint("ck_class_students_status", "status IN ('Active', 'Removed')");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("full_name");

                    b.Property<byte>("GradeLevel")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("grade_level");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("StudentId")
                        .HasName("pk_students");

                    b.HasAlternateKey("CenterId", "StudentId")
                        .HasName("ux_students_center_id_student_id");

                    b.HasIndex("CenterId", "GradeLevel")
                        .HasDatabaseName("ix_students_center_id_grade_level");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("ck_students_grade_level", "grade_level BETWEEN 10 AND 12");
                        });
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("subject_code");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("subject_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("SubjectId")
                        .HasName("pk_subjects");

                    b.HasAlternateKey("CenterId", "SubjectId")
                        .HasName("ux_subjects_center_id_subject_id");

                    b.HasIndex("CenterId", "SubjectCode")
                        .IsUnique()
                        .HasDatabaseName("ux_subjects_center_id_subject_code");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Bio")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("bio");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Department")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("department");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<ulong>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasDefaultValue(1ul)
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("TeacherId")
                        .HasName("pk_teachers");

                    b.HasAlternateKey("CenterId", "TeacherId")
                        .HasName("ux_teachers_center_id_teacher_id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.RefreshToken", b =>
                {
                    b.HasOne("EduTwin.DAL.IdentityAndTenancy.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("CenterId", "ReplacedByTokenId")
                        .HasPrincipalKey("CenterId", "RefreshTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by");

                    b.HasOne("EduTwin.DAL.IdentityAndTenancy.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("CenterId", "UserId")
                        .HasPrincipalKey("CenterId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_tenant");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.User", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_centers_tenant");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Class", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("CenterId", "SubjectId")
                        .HasPrincipalKey("CenterId", "SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_subjects_subject");

                    b.HasOne("EduTwin.DAL.Organization.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("CenterId", "TeacherId")
                        .HasPrincipalKey("CenterId", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_teachers_teacher");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.ClassStudent", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Class", "Class")
                        .WithMany("ClassStudents")
                        .HasForeignKey("CenterId", "ClassId")
                        .HasPrincipalKey("CenterId", "ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_students_classes_class");

                    b.HasOne("EduTwin.DAL.Organization.Student", "Student")
                        .WithMany()
                        .HasForeignKey("CenterId", "StudentId")
                        .HasPrincipalKey("CenterId", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_students_students_student");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Student", b =>
                {
                    b.HasOne("EduTwin.DAL.IdentityAndTenancy.User", "User")
                        .WithOne()
                        .HasForeignKey("EduTwin.DAL.Organization.Student", "CenterId", "StudentId")
                        .HasPrincipalKey("EduTwin.DAL.IdentityAndTenancy.User", "CenterId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_users_profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Subject", b =>
                {
                    b.HasOne("EduTwin.DAL.Organization.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_centers_tenant");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Teacher", b =>
                {
                    b.HasOne("EduTwin.DAL.IdentityAndTenancy.User", "User")
                        .WithOne()
                        .HasForeignKey("EduTwin.DAL.Organization.Teacher", "CenterId", "TeacherId")
                        .HasPrincipalKey("EduTwin.DAL.IdentityAndTenancy.User", "CenterId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_users_profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTwin.DAL.IdentityAndTenancy.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("EduTwin.DAL.Organization.Class", b =>
                {
                    b.Navigation("ClassStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
